sonar.projectKey=next-tt-fe
sonar.projectName=next-tt-fe
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.stories.tsx,src/**/*.d.ts,src/**/__tests__/**,src/**/__mocks__/**,.next/**,node_modules/**,coverage/**,.scannerwork/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.stories.tsx,src/**/__tests__/**,src/**/__mocks__/**

sonar.sourceEncoding=UTF-8